# Generated by Django 4.2.7 on 2025-11-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('passenger', 'Passenger'), ('driver', 'Driver'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
